CREATE TABLE TB_USUARIO (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome         VARCHAR2(100) NOT NULL,
  email        VARCHAR2(100) NOT NULL UNIQUE,
  senha        VARCHAR2(100) NOT NULL,
  latitude     NUMBER(9,6),
  longitude    NUMBER(9,6),
  dt_cadastro  DATE DEFAULT SYSDATE
);

CREATE TABLE TB_CULTURA (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome         VARCHAR2(100) NOT NULL,
  ciclo_dias   NUMBER,
  temp_min     NUMBER(5,2),
  temp_max     NUMBER(5,2),
  chuva_ideal  NUMBER(7,2),
  tipo_solo    VARCHAR2(50)
);

CREATE TABLE TB_ANALISE (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario  NUMBER NOT NULL,
  id_cultura  NUMBER NOT NULL,
  detalhes    VARCHAR2(500),
  latitude    NUMBER(9,6),
  longitude   NUMBER(9,6),
  dt_analise  DATE DEFAULT SYSDATE,
  CONSTRAINT fk_analise_usuario FOREIGN KEY (id_usuario) REFERENCES TB_USUARIO(id),
  CONSTRAINT fk_analise_cultura FOREIGN KEY (id_cultura) REFERENCES TB_CULTURA(id)
);

CREATE TABLE TB_RECOMENDACAO (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_analise  NUMBER NOT NULL,
  texto       CLOB,
  score       NUMBER,
  dt_geracao  DATE DEFAULT SYSDATE,
  CONSTRAINT fk_recom_analise FOREIGN KEY (id_analise) REFERENCES TB_ANALISE(id)
);

CREATE TABLE TB_CLIMA_HIST (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_analise   NUMBER NOT NULL,
  temp_media   NUMBER(5,2),
  chuva_mm     NUMBER(7,2),
  umidade      NUMBER(5,2),
  dt_registro  DATE DEFAULT SYSDATE,
  CONSTRAINT fk_clima_analise FOREIGN KEY (id_analise) REFERENCES TB_ANALISE(id)
);

CREATE TABLE TB_ALERTA (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario  NUMBER NOT NULL,
  id_cultura  NUMBER NOT NULL,
  tipo        VARCHAR2(50),
  mensagem    VARCHAR2(500),
  dt_alerta   DATE DEFAULT SYSDATE,
  CONSTRAINT fk_alerta_usuario FOREIGN KEY (id_usuario) REFERENCES TB_USUARIO(id),
  CONSTRAINT fk_alerta_cultura FOREIGN KEY (id_cultura) REFERENCES TB_CULTURA(id)
);